# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
