# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170327_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='description',
            new_name='text',
        ),
    ]
