# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170402_0956'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
