# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default=4, max_length=255),
            preserve_default=False,
        ),
    ]
