# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='comment',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
